import { CustomARN } from '@sls-mentor/arn';

import {
  listApiGatewaysV2,
  listBackupPlans,
  listCloudformationStacks,
  listCloudFrontDistributions,
  listCloudwatchLogGroups,
  listCognitoUserPools,
  listDynamoDBTables,
  listEventBridgeEventBuses,
  listGraphqlApis,
  listIamRoles,
  listLambdaFunctions,
  listRdsClusters,
  listRdsInstances,
  listRestApiGateways,
  listS3Buckets,
  listSecrets,
  listSESConfigurationSets,
  listSESIdentities,
  listSnsSubscriptions,
  listSnsTopics,
  listSqsQueues,
  listStateMachines,
} from './services';

export const listAllResourcesFromServices = async ({
  region,
}: {
  region: string;
}): Promise<CustomARN[]> => {
  const [
    s3buckets,
    lambdaFunctions,
    sqsQueues,
    cognitoUserPools,
    cloudWatchLogGroups,
    eventBridgeEventBuses,
    cloudFrontDistributions,
    rdsInstances,
    backupPlans,
    apiGatewaysV2,
    sesIdentities,
    snsTopics,
    snsSubscriptions,
    sesConfigurationSets,
    restApiGateways,
    dynamoDBTables,
    iamRoles,
    rdsClusters,
    stateMachines,
    graphqlApis,
    secretManegerSecrets,
    cloudformationStacks,
  ] = await Promise.all([
    listS3Buckets({ region }),
    listLambdaFunctions(),
    listSqsQueues(),
    listCognitoUserPools(),
    listCloudwatchLogGroups(),
    listEventBridgeEventBuses(),
    listCloudFrontDistributions(),
    listRdsInstances(),
    listBackupPlans(),
    listApiGatewaysV2(),
    listSESIdentities(),
    listSnsTopics(),
    listSnsSubscriptions(),
    listSESConfigurationSets(),
    listRestApiGateways(),
    listDynamoDBTables(),
    listIamRoles(),
    listRdsClusters(),
    listStateMachines(),
    listGraphqlApis(),
    listSecrets(),
    listCloudformationStacks(),
  ]);

  return [
    ...s3buckets,
    ...lambdaFunctions,
    ...sqsQueues,
    ...cognitoUserPools,
    ...cloudWatchLogGroups,
    ...eventBridgeEventBuses,
    ...cloudFrontDistributions,
    ...rdsInstances,
    ...backupPlans,
    ...apiGatewaysV2,
    ...sesIdentities,
    ...snsTopics,
    ...snsSubscriptions,
    ...sesConfigurationSets,
    ...restApiGateways,
    ...dynamoDBTables,
    ...iamRoles,
    ...rdsClusters,
    ...stateMachines,
    ...graphqlApis,
    ...secretManegerSecrets,
    ...cloudformationStacks.map(({ stackArn }) => stackArn),
  ];
};
