name: Guardian
description: Linting AWS Infrastructure for performance, security and sustainability optimization.
author: Frédéric Barthelet
inputs:
  repo-token:
    description: GitHub repository token for publishing inline lint annotations. Should be secrets.GITHUB_TOKEN.
    required: true
  level:
    description: 'Sls-mentor level'
    required: false
    default: '1'
  iam-role:
    description: 'IAM role to assume'
    required: false
    default: 'arn:aws:iam::463151931555:role/github-action'
runs:
  using: 'composite'
  steps:
    - name: 'configure aws credentials'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::463151931555:role/github-action
        aws-region: 'eu-west-1'
    - name: 'sls-mentor'
      run: echo 'toto' | yarn sls-mentor --level ${{ inputs.level }}
      shell: bash
