name: 'Install Node Dependencies'
description: 'Install monorepo dependencies using pnpm'
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
      shell: bash
