name: CI

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CI: true
  NODE_VERSION: 16

jobs:
  sls-mentor-action:
    name: SLS Mentor Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run sls-mentor-action-test
        uses: ./.github/actions/sls-mentor-action-test
        # GITHUB_TOKEN in forked repositories is read-only
        # https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
        if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }}
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
