name: CI

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CI: true
  NODE_VERSION: 16

jobs:
  sls-mentor-action:
    name: SLS Mentor Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.22.0
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
      - name: Install & cache node dependencies
        uses: ./.github/actions/install
      - name: Run sls-mentor-action-test
        uses: ./.github/actions/sls-mentor-action-test
